#!/bin/sh
# Molget: bash script to get coordinates from chemical name using Babel and Cactus
# usage: ./molget methane
# (remember to "chmod 755 molget)
#
# Original work by Prof. Jensen (https://github.com/jensengroup/molget).
#
molecule="$1"

url="https://cactus.nci.nih.gov/chemical/structure/$molecule/smiles"
url=$(echo "$url" | sed 's/ /%20/g')

curl "$url" -o "$molecule.smi"
babel -ismi "$molecule.smi" -oxyz "$molecule.xyz" --gen3D
